package com.example.simplelibrarymanagement.data.repository

import com.example.simplelibrarymanagement.domain.model.Book
import com.example.simplelibrarymanagement.domain.repository.BookRepository
import kotlinx.coroutines.delay
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class BookRepositoryImpl @Inject constructor() : BookRepository {

    private val books = mutableListOf(
        Book(
            id = "1",
            title = "Atomic Habits",
            author = "James Clear",
            year = 2018,
            description = "An easy and proven way to build good habits and break bad ones. Atomic Habits will reshape the way you think about progress and success, and give you the tools and strategies you need to transform your habits.",
            imageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385l/40121378.jpg",
            isAvailable = true,
            category = null
        ),
        Book(
            id = "2",
            title = "Sapiens: A Brief History of Humankind",
            author = "Yuval Noah Harari",
            year = 2011,
            description = "A groundbreaking narrative of humanity’s creation and evolution that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be 'human.'",
            imageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1420585954l/23692271.jpg",
            isAvailable = false,
            category = null
        )
    )

    override suspend fun getBookById(bookId: String): Book? {
        delay(500)
        return books.find { it.id == bookId }
    }

    override suspend fun getAllBooks(): List<Book> {
        delay(1000)
        return books
    }

    override suspend fun borrowBook(bookId: String) {
        delay(1000)
        val bookIndex = books.indexOfFirst { it.id == bookId }
        if (bookIndex != -1) {
            val book = books[bookIndex]
            books[bookIndex] = book.copy(isAvailable = false)
        }
    }

    override suspend fun addBook(book: Book) {
        delay(500) // Simulate network delay
        // In a real app, the ID would be generated by the backend.
        // Here, we just add it to the list.
        books.add(book.copy(id = (books.size + 1).toString()))
    }

    override suspend fun updateBook(book: Book) {
        delay(500) // Simulate network delay
        val index = books.indexOfFirst { it.id == book.id }
        if (index != -1) {
            books[index] = book
        }
    }

    override suspend fun deleteBook(bookId: String) {
        delay(500) // Simulate network delay
        books.removeAll { it.id == bookId }
    }
}